---
collections:
  - name: amazon.aws
    source: https://cloud.redhat.com/api/automation-hub/
  - name: cloud.terraform
    source: https://cloud.redhat.com/api/automation-hub/

  # TODO change to automation hub source when available
  - name: infra.aap_utilities
    source: https://galaxy.ansible.com
  - name: infra.controller_configuration
    source: https://galaxy.ansible.com

  - name: community.general
    source: https://galaxy.ansible.com

...
