---
- name: Destroy AAP infrastructure nodes with terraform
  hosts: '{{ target | default("localhost") }}'

  vars_files:
    - vars/terraform_aap.yml

  tasks:
    - name: Set terraform build directory fact
      ansible.builtin.set_fact:
        _tf_builddir: '{{ playbook_dir }}/tf_builds/{{ terraform_build_name }}'

    - name: Destroy AAP infrastructure
      cloud.terraform.terraform:
        project_path: '{{ _tf_builddir }}'
        state: absent

    - name: Delete playbook-generated files
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ _tf_builddir }}/terraform.tfvars'
        - '{{ playbook_dir }}/inventory/terraform_provider.yml'

    - name: Remove terraform S3 bucket backend
      amazon.aws.s3_bucket:
        name: '{{ terraform_state_aws_bucket }}'
        region: '{{ terraform_state_aws_region }}'
        state: absent
        force: true
      when: delete_s3_backend | default(false) | bool

...
# vim: ft=yaml.ansible
