---
- name: Generate inventory from terraform state
  hosts: localhost

  vars_files:
    - vars/terraform_aap.yml

  tasks:
    - name: Add AAP hosts to running inventory
      block:
        - name: Add bastion host to inventory
          ansible.builtin.add_host:
            name: '{{ lookup("cloud.terraform.tf_output", "bastion_public_fqdn", project_path=terraform_local_dir) }}'
            groups: bastion
            ansible_user: ec2-user

        - name: Add controller hosts to inventory
          ansible.builtin.add_host:
            name: '{{ item }}'
            groups: controller
            ansible_user: ec2-user
          loop: '{{ lookup("cloud.terraform.tf_output", "controller_public_fqdns", project_path=terraform_local_dir) }}'

        - name: Add hub hosts to inventory
          ansible.builtin.add_host:
            name: '{{ item }}'
            groups: hub
            ansible_user: ec2-user
          loop: '{{ lookup("cloud.terraform.tf_output", "hub_public_fqdns", project_path=terraform_local_dir) }}'

        - name: Add database hosts to inventory
          ansible.builtin.add_host:
            name: '{{ item }}'
            groups: database
            ansible_user: ec2-user
          loop: '{{ lookup("cloud.terraform.tf_output", "database_private_fqdns", project_path=terraform_local_dir) }}'

        - name: Add execution nodes to inventory
          ansible.builtin.add_host:
            name: '{{ item }}'
            groups: execution
            ansible_user: ec2-user
          loop: '{{ lookup("cloud.terraform.tf_output", "execution_public_fqdns", project_path=terraform_local_dir) }}'

...
# vim: ft=yaml.ansible
